// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmrtGfv7yAV4OClPVFdHOlNpKpj5fw97o',
    appId: '1:806425448011:web:486ef4b1607a1354a107ce',
    messagingSenderId: '806425448011',
    projectId: 'privacy-id-system',
    authDomain: 'privacy-id-system.firebaseapp.com',
    storageBucket: 'privacy-id-system.firebasestorage.app',
    measurementId: 'G-VHZS79T249',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWe1OMP9qwHM9PbhU2lLASIcDB1Re01c4',
    appId: '1:806425448011:android:50c900a6d8a144dba107ce',
    messagingSenderId: '806425448011',
    projectId: 'privacy-id-system',
    storageBucket: 'privacy-id-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzX8EocewUv1u9T8mEbQpoVll113VAVQ',
    appId: '1:806425448011:ios:bc75ccf732d82cf5a107ce',
    messagingSenderId: '806425448011',
    projectId: 'privacy-id-system',
    storageBucket: 'privacy-id-system.firebasestorage.app',
    iosBundleId: 'com.example.privacyIdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzX8EocewUv1u9T8mEbQpoVll113VAVQ',
    appId: '1:806425448011:ios:bc75ccf732d82cf5a107ce',
    messagingSenderId: '806425448011',
    projectId: 'privacy-id-system',
    storageBucket: 'privacy-id-system.firebasestorage.app',
    iosBundleId: 'com.example.privacyIdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmrtGfv7yAV4OClPVFdHOlNpKpj5fw97o',
    appId: '1:806425448011:web:0a06111a1c068b46a107ce',
    messagingSenderId: '806425448011',
    projectId: 'privacy-id-system',
    authDomain: 'privacy-id-system.firebaseapp.com',
    storageBucket: 'privacy-id-system.firebasestorage.app',
    measurementId: 'G-85P5MG2J3M',
  );

}